# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env: 
          POSTGRES_USER: waiters
          POSTGRES_PASSWORD: waiters123
          POSTGRES_DB: waiters_app
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
            
            - name: create postgresql tables
      run:- name: create postgresql tables
      run:  PGPASSWORD=waiters123 psql -h localhost -U waiters -d waiters_app -a -f ./waiterAppFunction/sql/tables.sql
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        PSQLConnectionString: Host=localhost;Username=waiters;Password=waiters123;Database=waiters_app
